name: matrix strat
on: workflow_dispatch
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup python
        uses: action/setup-python@v5
        with:
          python-version: "3.13"
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: run linter
        run: flake8 app.py
