name: dus dus
on: workflow_dispatch

jobs:
  greet:
    runs-on: self-hosted

    steps:
      - name: Update system
        run: sudo apt update

      - name: Install Python
        run: sudo apt install -y python3 python3-pip

      - name: Run Python addition
        run: |
          python3 -c "a=5; b=7; print('Sum =', a+b)"
      - name: Debug
        run: |
          echo "Running on EC2"
          hostname
          whoami
