name: dus dus
on: workflow_dispatch

jobs:
  greet:
    runs-on: self-hosted

    steps:
      - name: Update system
        run: sudo apt update
      - name: Debug
        run: |
          echo "Running on EC2"
          hostname
          whoami
