name: nice

on:
  push:
    branches: [main]
    paths:
      - '**.html'

jobs:
  sayW:
    runs-on: ubuntu-latest
    steps:
      - name: WSPEED
        run: echo "W SPEED"    
      - name: LSPEED
        run: echo "L SPEED"
